# Test dummy ansible playbook
---

- hosts: servers
  vars_files:
    - vagrant.yml
  tasks:
    - name: Create dummy file
      copy:
        content: '{{ new_file_content }}'
        dest: '{{ test_file }}'

    - name: Read test file content
      slurp:
        src: '{{ test_file }}'
      register: file_content

    - name: Print test file content
      debug:
        msg: "{{ file_content.content | b64decode }}"
